- id: '1542493934447'
  alias: make next automation here
  trigger: []
  condition: []
  action: []
- id: '1542581288690'
  alias: Sunset Lights
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.sunroom_north
    service: homeassistant.turn_on
  - data:
      entity_id: switch.sliding_door
    service: homeassistant.turn_on
- id: '1542582786796'
  alias: Goodnight Shutdown
  trigger:
  - at: '22:15'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sunroom_south
    service: homeassistant.turn_off
  - data:
      entity_id: switch.sunroom_north
    service: homeassistant.turn_off
  - data:
      entity_id: switch.sliding_door
    service: homeassistant.turn_off
