
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

tplink:
  discovery: false
  switch:
    #b0:4e:26:f5:f5:eb  sliding door      HS105
    - host: 192.168.86.93

    #b0:4e:26:f5:dc:5d  sunroom south     HS105
    - host: 192.168.86.92

    #70:4f:57:84:a7:2e  living room north HS100
    - host: 192.168.86.43

    #d8:0d:17:d3:1c:c8  acorn             HS103
    - host: 192.168.86.32

    #b0:4e:26:f5:dc:53  sunroom north     HS105
    - host: 192.168.86.99

cover:
  #garage door automation via cloud
  - platform: myq
    username: !secret myQ_user
    password: !secret myQ_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

