
homeassistant:
  # Name of the location where Home Assistant is running
  name: Redberry
  # Location required to calculate the time the sun rises and sets
  latitude: 41.693
  longitude: -83.7273
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 203
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Time
sensor:
  - platform: time_date
    display_options:
      - 'date_time'

# Scenes
scene:
  - name: Morning
    entities:
     switch.Sunroom_North: on
     switch.Living_Room_North: on

#kasa switches
switch:
  - platform: tplink
    name: Sliding Door
    host: 192.168.86.93
  - platform: tplink
    name: Sunroom North
    host: 192.168.86.91
  - platform: tplink
    name: Sunroom South
    host: 192.168.86.92

automation: !include automations.yaml
script: !include scripts.yaml
